spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: testuser
    password: somepassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true




